### ISSUE TITLE
Task2

### ISSUE THREAD

**Issue by YakutovDmitriy** [rinnifox/pats_bio-python-course-homework#2]
Tests for first hw is ok!

Please rename functions in like `add_border -> addBorder` so I could test them. If you don't want to do that you can create variable `addBorder` and assign it value of `add_border`.

Also your source code doesn't satisfy pep rules. Please fix it.

**Comment by rinnifox** [comment]
I've corrected functions' names but, actually, I'd changed them before to the lowercase with underscores just due to PEP8 requirements. 

It turned out that in PyCharm the length of the line was set to 120 characters, while PEP8 permits only 79. So now it seems to be ok.

However, in line 24, when I inserted a break before "+" and then checked the code in bash cell - it showed a mistake: 

> W503 line break before binary operator 

But at https://www.python.org/dev/peps/pep-0008/?#should-a-line-break-before-or-after-a-binary-operator it is said: 
```
# No: operators sit far away from their operands
income = (gross_wages +
          taxable_interest +
          (dividends - qualified_dividends) -
          ira_deduction -
          student_loan_interest)

# Yes: easy to match operators with operands
income = (gross_wages
          + taxable_interest
          + (dividends - qualified_dividends)
          - ira_deduction
          - student_loan_interest)
```
And after giving the examples they conclude: 

> "In Python code, it is permissible to break before or after a binary operator, as long as the convention is consistent locally. For new code Knuth's style is suggested".

So I don't quite understand why PEP8 marks this as a mistake while checking "pep8 task2.py"... 
PyCharm accepts both options.

**Comment by YakutovDmitriy** [comment]
You can take `pep` rules not so seriously. If there are some uncertainties you can act at your own.
Also there are some style rules that are not checked by `pep` but they are vey important among most programmers. One of them is spaces around binary operators (e.g. `'|'+elem+'|'` -> `'|' + elem + '|'`. Please use this rule in future. 

About functions. 
Functions `addBorder` and `goodPairs` contain some mistakes.
`addBorder`:  `IndexError` on some tests.
`goodPairs`: Wrong answer on some tests.
Try to find bug in code or misunderstanding of the statements and fix these functions.
Other functions are ok.

**Comment by YakutovDmitriy** [comment]
And about variables and functions names style.
Actually python likes lowercase with underscores, but I like camelcase-style. We learn how to use python, so I'll name future homeworks functions using lowercase only :sob:

**Comment by rinnifox** [comment]
I've corrected some mistakes but I'm not sure this covers all the issues you'd found before :smile: 

Basically, in addBorder I've taken into the account the case, when we have only 1 string in the list - it seems this was the problem of IndexError. In goodPairs I've just transformed the list to the set to exclude the repetitions.

**Comment by YakutovDmitriy** [comment]
Good, your new implementations are ok!
